linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - cyclop
    - decorder
    - durationcheck
    - errcheck
    - execinquery
    - exhaustive
    - exhaustruct
    - goconst
    - gofmt
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nestif
    - nosprintfhostport
    - prealloc
    - reassign
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wsl
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true
